apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: guido-deployment
  labels: 
    app: guido
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guido
  template:
    metadata:
      labels:
        app: guido
    spec:
      containers:
        - name: guido
          image: ronualdo/guido:v0.0.1
          ports:
            - containerPort: 4000
